### ISSUE TITLE
Set Focus issue

### ISSUE THREAD

**Issue by Gingy92** [Mikeprod/FriendGroups#12]
Get this error when trying to set focus to someone.

1x [ADDON_ACTION_FORBIDDEN] AddOn 'FriendGroups' tried to call the protected function 'FocusUnit()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `FocusUnit'
FrameXML\UnitPopup.lua:1796: in function <FrameXML\UnitPopup.lua:1592>
[C]: in function `func'
FrameXML\UIDropDownMenu.lua:935: in function `UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

**Comment by Mikeprod** [comment]
Does this still happens ? Tested on basic UI and with SUF, without any issue. Closing this next time I read this if no updates.

**Comment by Gingy92** [comment]
I'm not even sure. Haven't played in 3+ months and don't plan on coming
back. Sorry mate.

**Comment by Mikeprod** [comment]
OK thanks I will reopen it if someone else reports it. Have fun without WoW
