### ISSUE TITLE
Invite/request to join group buttons are disabled when the addon is enabled.

### ISSUE THREAD

**Issue by xeropresence** [Mikeprod/FriendGroups#13]
Something seems to have broken recently with this. 
Even with all other addons disabled, having friendgroups enabled causes all of the invite/request to join group buttons to become disabled.

**Comment by xeropresence** [comment]
Looks like FriendsFrame.lua has been updated, 

local INVITE_RESTRICTION_NONE = 6;

has been added among other changes, 

FriendsFrame_GetInviteRestriction seems to return 1 or 6 for most of my friends.

**Comment by k99k5** [comment]
local INVITE_RESTRICTION_NO_GAME_ACCOUNTS = 0;
local INVITE_RESTRICTION_CLIENT = 1;
local INVITE_RESTRICTION_LEADER = 2;
local INVITE_RESTRICTION_FACTION = 3;
local INVITE_RESTRICTION_INFO = 4;
local INVITE_RESTRICTION_REGION = 5;
local INVITE_RESTRICTION_NONE = 6;
