### ISSUE TITLE
Error promoting a guild members rank

### ISSUE THREAD

**Issue by mbabigian** [Mikeprod/FriendGroups#15]
1x [ADDON_ACTION_FORBIDDEN] AddOn 'FriendGroups' tried to call the protected function 'SetGuildRankOrder()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `SetGuildRankOrder'
Blizzard_Communities\GuildRoster.lua:174: in function `func'
FrameXML\UIDropDownMenu.lua:914: in function `UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

**Comment by Mikeprod** [comment]
Does this still happens ? I cannot test it because I have not any guild permissions to do such action. Closing this next time I read this if no updates.

**Comment by Mikeprod** [comment]
It would appear to be still the case, the option menu is tainting the secure blizzard UI. The only solution so far is to reload the interface and promote afterwards.
