### ISSUE TITLE
Invite to group broken again

### ISSUE THREAD

**Issue by xeropresence** [Mikeprod/FriendGroups#16]
Looks like checking if you can invite a player is broken again. I've had some other errors on and off when groups were created and removed from lfg while the tab was open as well.

**Comment by Mikeprod** [comment]
Thank you for your feedback I'll check when 8.2 releases tomorrow on EU.

**Comment by xeropresence** [comment]
local INVITE_RESTRICTION_NO_GAME_ACCOUNTS = 0;
local INVITE_RESTRICTION_CLIENT = 1;
local INVITE_RESTRICTION_LEADER = 2;
local INVITE_RESTRICTION_FACTION = 3;
local INVITE_RESTRICTION_INFO = 4;
local INVITE_RESTRICTION_WOW_PROJECT_ID = 5;
local INVITE_RESTRICTION_WOW_PROJECT_MAINLINE = 6;
local INVITE_RESTRICTION_WOW_PROJECT_CLASSIC = 7;
local INVITE_RESTRICTION_NONE = 8;
local INVITE_RESTRICTION_MOBILE = 9;


adding this to friendsgroup fixes the invite to group stuff, but sorting is messed up atm as well, probably need to diff the two files

**Comment by Mikeprod** [comment]
Thanks for the quick fix, for the invite, I will look into the sorting if I have time this end of the week

**Comment by Mikeprod** [comment]
Closing this with the #18 proposition. Branch update/8.2.5 should reflect the work on fixing this before merging on master.
