### ISSUE TITLE
"FriendsGroups has been blocked from an action..."

### ISSUE THREAD

**Issue by zeress** [Mikeprod/FriendGroups#2]
"FriendsGroups has been blocked from an action only available to the Blizzard UI. You can  disable this addon and reload the UI"

When trying to queue for PvP using the casual tab I am getting blocked by the UI when clicking the join battle button. Disabling friendgroups does resolves the issue.

The UI element in question is "HonorFrameQueueButton"

Thanks for any help and continuing support

**Comment by Mikeprod** [comment]
It is now fixed. I'll let you close this issue if you agree with me.

**Comment by Mikeprod** [comment]
I knew my last fix was not the right solution ;)

**Comment by Mikeprod** [comment]
Well my morning fix wrong other scrolling bars ....

**Comment by Mikeprod** [comment]
I have fixed it, then I'll let you close this issue when you can acknowledge the fix.

**Comment by zeress** [comment]
With the newest fix, r7.1.3Fixed, it now works. Thanks!
