### ISSUE TITLE
Breaks Scrolling on Achievements

### ISSUE THREAD

**Issue by izzy420** [Mikeprod/FriendGroups#3]
addon enabled breaks scrolling though achievements pane

edit* also breaks it in other UI frames like class halls

disabling it makes it work again

**Comment by Mikeprod** [comment]
Did you use the last version ?

**Comment by Mikeprod** [comment]
Well the fix from this morning has to be more complicated that it is now :/

**Comment by Norayyn** [comment]
instead of making a new thread ^^ 
when it's enabled i can't scroll in the Guild Panel :)
Once turned off you can tho

**Comment by Mikeprod** [comment]
Yes I know. My last push fixes all the currently open issues. Updating on curse right now

**Comment by izzy420** [comment]
i acknowledge the fix but there is a new bug thats only reproduce-able  if you scroll friends list it affects chat scrolling

scrolling friends up or down makes chatbox scroll up regardless

http://i.imgur.com/YGnLNsO.jpg

**Comment by Mikeprod** [comment]
Well I tried a thing, but I did not notice it affected the chat. It should normally be all good. I have not updated Curse yet, I will do it tomorrow.

**Comment by Mikeprod** [comment]
Curse updated
