### ISSUE TITLE
expand and colapse groups not always working

### ISSUE THREAD

**Issue by puck-github** [Mikeprod/FriendGroups#36]
usually 3rd group down only works initially.

**Comment by Mikeprod** [comment]
Hey, I am aware of such behavior, I never found out why.

**Comment by puck-github** [comment]
`local divider = scrollFrame.dividerPool:Acquire()`
the click seems to work fine after i removed the dividers. so i assume they are interfering somehow at times. bit random though.

**Comment by Mikeprod** [comment]
I will look into it ...

**Comment by Mikeprod** [comment]
Removed the divider in 07f255fd5e3bb1ba55c94b9bd8fdc6dec012e276
