### ISSUE TITLE
8.2.5 Lua Error for FriendGroup

### ISSUE THREAD

**Issue by acps87** [Mikeprod/FriendGroups#39]
I started getting the follow Lua error in my bugsack with patch 8.2.5:

1x FriendGroups\FriendGroups-8.2-fix6.lua:6: hooksecurefunc(): FriendsFrameTooltip_Show is not a function
[C]: in function `hooksecurefunc'
FriendGroups\FriendGroups-8.2-fix6.lua:6: in function <FriendGroups\FriendGroups.lua:3>
FriendGroups\FriendGroups-8.2-fix6.lua:980: in function <FriendGroups\FriendGroups.lua:969>

Locals:

**Comment by mudohir** [comment]
I've fixed a few of these errors locally.
FriendsFrameTooltip_Show should be replaced with HybridScrollFrame_Update
The proper template for the friend list button is now "FriendsListButtonTemplate"
BNGetFriendGameAccountInfo() has been removed.  C_BattleNet.GetFriendAccountInfo() replaces it

There are some changes in FriendsFrame.lua for a few of the methods that should be taken into account for the new implementations in the addon.

**Comment by mudohir** [comment]
I've managed to fix pretty much every issue with this addon in 8.2.5 will clone and setup a PR.

**Comment by kahlano** [comment]
> I've managed to fix pretty much every issue with this addon in 8.2.5 will clone and setup a PR.

Great! I hope you share your work!

**Comment by Mikeprod** [comment]
As I commented on your PR, thanks a lot, even though I was close to a solution on my end this week.

**Comment by Mikeprod** [comment]
Hopefully I will get it released this weekend if I have the time. Why do I have a social life ? XD

**Comment by kahlano** [comment]
social life ? what is that :D

**Comment by Mikeprod** [comment]
There was a bug with a class not being set, I think I fixed it with tonight's release. Closing this 8.2.5 issue :)
