### ISSUE TITLE
[REQ] Hide Offline / Offline Group

### ISSUE THREAD

**Issue by kronflux** [Mikeprod/FriendGroups#8]
I'd love to see one of two options.
Either a way to hide all offline from groups, or(which may actually be better) Group all offline people into a group called "Offline", and not show them as offline in the groups you've assigned.

**Comment by Mikeprod** [comment]
There is already an option for that. Have you tried right clicking on a group, then go on settings and check hide all offline option ?

**Comment by kronflux** [comment]
Ah! yes! I didn't try right clicking groups at all. I was looking for an actual settings menu in Interface > Addons.

Unfortunately there's not much documentation I could find on the Curse page, nor the GitHub.

Thanks! Perhaps consider adding some details about all available options on both the Curse addon page and the README on here :)

Cheers!
